name: clipzy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  hugeicons: ^0.0.11
  camera: ^0.10.5+9
  video_player: ^2.8.6
  flutter_sound: ^9.2.13
  file_picker: ^10.2.0
  image: ^4.2.0
  permission_handler: ^11.3.1
  google_sign_in: ^7.1.1
  ffmpeg_kit_flutter_new: ^2.0.0
  sticker_view: ^0.0.4
  image_picker: ^1.0.7
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
