// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-_pxD_Dm0GujILwY2n3i48IFusk0wJuM',
    appId: '1:252607465611:web:8371bca6b31b3f1746ec8e',
    messagingSenderId: '252607465611',
    projectId: 'clipzy-54a55',
    authDomain: 'clipzy-54a55.firebaseapp.com',
    storageBucket: 'clipzy-54a55.firebasestorage.app',
    measurementId: 'G-DS8MT9FES4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0nUtlI6Mme3IJHJz8kOMIQ1UvGNZoINs',
    appId: '1:252607465611:android:b2fe6db1c2b6f5e446ec8e',
    messagingSenderId: '252607465611',
    projectId: 'clipzy-54a55',
    storageBucket: 'clipzy-54a55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxenRVjxwLlR74k1QXuAnKBCFes5KE3wg',
    appId: '1:252607465611:ios:4da677ae96ed88e446ec8e',
    messagingSenderId: '252607465611',
    projectId: 'clipzy-54a55',
    storageBucket: 'clipzy-54a55.firebasestorage.app',
    iosBundleId: 'com.example.clipzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxenRVjxwLlR74k1QXuAnKBCFes5KE3wg',
    appId: '1:252607465611:ios:4da677ae96ed88e446ec8e',
    messagingSenderId: '252607465611',
    projectId: 'clipzy-54a55',
    storageBucket: 'clipzy-54a55.firebasestorage.app',
    iosBundleId: 'com.example.clipzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-_pxD_Dm0GujILwY2n3i48IFusk0wJuM',
    appId: '1:252607465611:web:72675012e442f0b946ec8e',
    messagingSenderId: '252607465611',
    projectId: 'clipzy-54a55',
    authDomain: 'clipzy-54a55.firebaseapp.com',
    storageBucket: 'clipzy-54a55.firebasestorage.app',
    measurementId: 'G-NE078WW0KN',
  );
}
